import type { Dish } from '@/types';

export const DISH_SEEDS: Dish[] = [
  // Kitchen 1 — مطبخ أم سمية (Maadi)
  {
    id: 'dish-1',
    kitchenId: 'kitchen-1',
    name: 'كشري',
    nameEn: 'Koshari',
    description: 'كشري مصري أصيل بالصلصة الحارة والدقة',
    descriptionEn: 'Authentic Egyptian koshari with spicy sauce and daqa',
    price: 65,
    category: 'أصناف رئيسية',
    categoryEn: 'Main Dishes',
    prepTime: 30,
    maxPortions: 20,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-10T08:00:00.000Z',
  },
  {
    id: 'dish-2',
    kitchenId: 'kitchen-1',
    name: 'شوربة عدس',
    nameEn: 'Lentil Soup',
    description: 'شوربة عدس صفرا دافية ومغذية',
    descriptionEn: 'Warm and nourishing yellow lentil soup',
    price: 40,
    category: 'شوربات',
    categoryEn: 'Soups',
    prepTime: 20,
    maxPortions: 15,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-10T08:00:00.000Z',
  },
  {
    id: 'dish-3',
    kitchenId: 'kitchen-1',
    name: 'مكرونة بشاميل',
    nameEn: 'Macaroni Bechamel',
    description: 'مكرونة بالباشاميل في الفرن زي البيت',
    descriptionEn: 'Oven-baked macaroni bechamel just like home',
    price: 75,
    category: 'أصناف رئيسية',
    categoryEn: 'Main Dishes',
    prepTime: 45,
    maxPortions: 15,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-10T08:00:00.000Z',
  },
  {
    id: 'dish-4',
    kitchenId: 'kitchen-1',
    name: 'سلطة خضرا',
    nameEn: 'Green Salad',
    description: 'سلطة طازة مع طماطم وخيار وبصل',
    descriptionEn: 'Fresh salad with tomatoes, cucumbers, and onions',
    price: 25,
    category: 'سلطات',
    categoryEn: 'Salads',
    prepTime: 10,
    maxPortions: 25,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-10T08:00:00.000Z',
  },
  {
    id: 'dish-5',
    kitchenId: 'kitchen-1',
    name: 'رز بلبن',
    nameEn: 'Rice Pudding',
    description: 'رز بلبن محلى بالقشطة',
    descriptionEn: 'Creamy sweet rice pudding',
    price: 35,
    category: 'حلويات',
    categoryEn: 'Sweets',
    prepTime: 60,
    maxPortions: 10,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-10T08:00:00.000Z',
  },
  // Kitchen 2 — مطبخ حاج محمد (Zamalek)
  {
    id: 'dish-6',
    kitchenId: 'kitchen-2',
    name: 'مشويات مشكلة',
    nameEn: 'Mixed Grill',
    description: 'مشويات مشكلة لحم وكفتة وشيش طاووق',
    descriptionEn: 'Mixed grill with beef, kofta, and chicken shish',
    price: 180,
    category: 'مشويات',
    categoryEn: 'Grills',
    prepTime: 45,
    maxPortions: 10,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-09T10:00:00.000Z',
  },
  {
    id: 'dish-7',
    kitchenId: 'kitchen-2',
    name: 'كفتة مشوية',
    nameEn: 'Grilled Kofta',
    description: 'كفتة لحم مشوية على الفحم',
    descriptionEn: 'Charcoal-grilled beef kofta',
    price: 120,
    category: 'مشويات',
    categoryEn: 'Grills',
    prepTime: 30,
    maxPortions: 12,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-09T10:00:00.000Z',
  },
  {
    id: 'dish-8',
    kitchenId: 'kitchen-2',
    name: 'شيش طاووق',
    nameEn: 'Chicken Shish',
    description: 'شيش طاووق متبل ومشوي',
    descriptionEn: 'Marinated and grilled chicken shish',
    price: 110,
    category: 'مشويات',
    categoryEn: 'Grills',
    prepTime: 35,
    maxPortions: 10,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-09T10:00:00.000Z',
  },
  {
    id: 'dish-9',
    kitchenId: 'kitchen-2',
    name: 'مقبلات مشكلة',
    nameEn: 'Mixed Appetizers',
    description: 'حمص ومتبل وبابا غنوج وسلطة طحينة',
    descriptionEn: 'Hummus, mutabbal, baba ghanoush, and tahini salad',
    price: 55,
    category: 'مقبلات',
    categoryEn: 'Appetizers',
    prepTime: 15,
    maxPortions: 20,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-09T10:00:00.000Z',
  },
  {
    id: 'dish-10',
    kitchenId: 'kitchen-2',
    name: 'فطيرة لحم',
    nameEn: 'Meat Pie',
    description: 'فطيرة لحم مع جبنة في العجينة',
    descriptionEn: 'Meat pie with cheese in the dough',
    price: 45,
    category: 'فطائر',
    categoryEn: 'Pastries',
    prepTime: 40,
    maxPortions: 15,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-09T10:00:00.000Z',
  },
  // Kitchen 3 — مطبخ ست نونه (Heliopolis)
  {
    id: 'dish-11',
    kitchenId: 'kitchen-3',
    name: 'بسبوسة',
    nameEn: 'Basbousa',
    description: 'بسبوسة هنية بالشربات والقشطة',
    descriptionEn: 'Sweet basbousa with syrup and cream',
    price: 50,
    category: 'حلويات',
    categoryEn: 'Sweets',
    prepTime: 60,
    maxPortions: 20,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-08T09:00:00.000Z',
  },
  {
    id: 'dish-12',
    kitchenId: 'kitchen-3',
    name: 'كنافة نابلسي',
    nameEn: 'Nabulsi Kunafa',
    description: 'كنافة بالجبنة والقطر',
    descriptionEn: 'Kunafa with cheese and syrup',
    price: 70,
    category: 'حلويات',
    categoryEn: 'Sweets',
    prepTime: 45,
    maxPortions: 15,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-08T09:00:00.000Z',
  },
  {
    id: 'dish-13',
    kitchenId: 'kitchen-3',
    name: 'أم علي',
    nameEn: 'Om Ali',
    description: 'أم علي بالمكسرات والقشطة',
    descriptionEn: 'Om Ali with nuts and cream',
    price: 55,
    category: 'حلويات',
    categoryEn: 'Sweets',
    prepTime: 30,
    maxPortions: 12,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-08T09:00:00.000Z',
  },
  {
    id: 'dish-14',
    kitchenId: 'kitchen-3',
    name: 'قطايف',
    nameEn: 'Qatayef',
    description: 'قطايف محشية جبنة أو مكسرات',
    descriptionEn: 'Qatayef stuffed with cheese or nuts',
    price: 60,
    category: 'حلويات',
    categoryEn: 'Sweets',
    prepTime: 35,
    maxPortions: 15,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-08T09:00:00.000Z',
  },
  {
    id: 'dish-15',
    kitchenId: 'kitchen-3',
    name: 'محشي ورق عنب',
    nameEn: 'Stuffed Grape Leaves',
    description: 'محشي ورق عنب بالأرز والطماطم',
    descriptionEn: 'Rice and tomato stuffed grape leaves',
    price: 80,
    category: 'أصناف رئيسية',
    categoryEn: 'Main Dishes',
    prepTime: 90,
    maxPortions: 10,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-08T09:00:00.000Z',
  },
  // Kitchen 4 — أكل البيت (Nasr City)
  {
    id: 'dish-16',
    kitchenId: 'kitchen-4',
    name: 'فول مدمس',
    nameEn: 'Ful Medames',
    description: 'فول مدمس بالزيت الحار والليمون',
    descriptionEn: 'Ful medames with hot oil and lemon',
    price: 30,
    category: 'أصناف رئيسية',
    categoryEn: 'Main Dishes',
    prepTime: 15,
    maxPortions: 30,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-07T11:00:00.000Z',
  },
  {
    id: 'dish-17',
    kitchenId: 'kitchen-4',
    name: 'طعمية',
    nameEn: 'Taameya',
    description: 'طعمية مصرية مقرمشة بالفول والكسبرة',
    descriptionEn: 'Crispy Egyptian falafel with fava beans and coriander',
    price: 35,
    category: 'مقبلات',
    categoryEn: 'Appetizers',
    prepTime: 20,
    maxPortions: 25,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-07T11:00:00.000Z',
  },
  {
    id: 'dish-18',
    kitchenId: 'kitchen-4',
    name: 'شوربة خضار',
    nameEn: 'Vegetable Soup',
    description: 'شوربة خضار طازة بالدجاج',
    descriptionEn: 'Fresh vegetable soup with chicken',
    price: 45,
    category: 'شوربات',
    categoryEn: 'Soups',
    prepTime: 25,
    maxPortions: 15,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-07T11:00:00.000Z',
  },
  {
    id: 'dish-19',
    kitchenId: 'kitchen-4',
    name: 'صينية فرخة',
    nameEn: 'Baked Chicken Tray',
    description: 'صينية فرخة بالبطاطس في الفرن',
    descriptionEn: 'Oven-baked chicken tray with potatoes',
    price: 130,
    category: 'أصناف رئيسية',
    categoryEn: 'Main Dishes',
    prepTime: 60,
    maxPortions: 8,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-07T11:00:00.000Z',
  },
  {
    id: 'dish-20',
    kitchenId: 'kitchen-4',
    name: 'عصير برتقان',
    nameEn: 'Orange Juice',
    description: 'عصير برتقان طازة',
    descriptionEn: 'Freshly squeezed orange juice',
    price: 25,
    category: 'مشروبات',
    categoryEn: 'Drinks',
    prepTime: 5,
    maxPortions: 30,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-07T11:00:00.000Z',
  },
  // Kitchen 5 — مطبخ السيدة (Dokki)
  {
    id: 'dish-21',
    kitchenId: 'kitchen-5',
    name: 'شوربة مكرونة',
    nameEn: 'Noodle Soup',
    description: 'شوربة مكرونة بالدجاج والخضار',
    descriptionEn: 'Chicken noodle soup with vegetables',
    price: 45,
    category: 'شوربات',
    categoryEn: 'Soups',
    prepTime: 25,
    maxPortions: 15,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-06T07:00:00.000Z',
  },
  {
    id: 'dish-22',
    kitchenId: 'kitchen-5',
    name: 'شوربة طماطم',
    nameEn: 'Tomato Soup',
    description: 'شوربة طماطم بالريحان والكريمة',
    descriptionEn: 'Tomato soup with basil and cream',
    price: 40,
    category: 'شوربات',
    categoryEn: 'Soups',
    prepTime: 20,
    maxPortions: 15,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-06T07:00:00.000Z',
  },
  {
    id: 'dish-23',
    kitchenId: 'kitchen-5',
    name: 'سلطة سيزر',
    nameEn: 'Caesar Salad',
    description: 'سلطة سيزر بالدجاج المشوي والبارميزان',
    descriptionEn: 'Caesar salad with grilled chicken and parmesan',
    price: 65,
    category: 'سلطات',
    categoryEn: 'Salads',
    prepTime: 15,
    maxPortions: 12,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-06T07:00:00.000Z',
  },
  {
    id: 'dish-24',
    kitchenId: 'kitchen-5',
    name: 'حمص بالطحينة',
    nameEn: 'Hummus with Tahini',
    description: 'حمص بالطحينة والزيت',
    descriptionEn: 'Hummus with tahini and olive oil',
    price: 35,
    category: 'مقبلات',
    categoryEn: 'Appetizers',
    prepTime: 10,
    maxPortions: 20,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-06T07:00:00.000Z',
  },
  // Kitchen 6 — فرن المعجنات (Mohandessin)
  {
    id: 'dish-25',
    kitchenId: 'kitchen-6',
    name: 'فطيرة جبنة',
    nameEn: 'Cheese Pie',
    description: 'فطيرة جبنة طازة من الفرن',
    descriptionEn: 'Freshly baked cheese pie',
    price: 40,
    category: 'فطائر',
    categoryEn: 'Pastries',
    prepTime: 25,
    maxPortions: 20,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-05T06:00:00.000Z',
  },
  {
    id: 'dish-26',
    kitchenId: 'kitchen-6',
    name: 'فطير مشلتت',
    nameEn: 'Feteer Meshaltet',
    description: 'فطير مشلتت بالسمن البلدي والعسل',
    descriptionEn: 'Flaky layered pastry with ghee and honey',
    price: 55,
    category: 'فطائر',
    categoryEn: 'Pastries',
    prepTime: 30,
    maxPortions: 15,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-05T06:00:00.000Z',
  },
  {
    id: 'dish-27',
    kitchenId: 'kitchen-6',
    name: 'بيتزا رقاق',
    nameEn: 'Rqaq Pizza',
    description: 'رقاق باللحم المفروم والطماطم',
    descriptionEn: 'Thin crust with minced beef and tomatoes',
    price: 60,
    category: 'فطائر',
    categoryEn: 'Pastries',
    prepTime: 35,
    maxPortions: 12,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-05T06:00:00.000Z',
  },
  {
    id: 'dish-28',
    kitchenId: 'kitchen-6',
    name: 'شاي كرك',
    nameEn: 'Karak Tea',
    description: 'شاي كرك بالحليب والهيل',
    descriptionEn: 'Karak tea with milk and cardamom',
    price: 20,
    category: 'مشروبات',
    categoryEn: 'Drinks',
    prepTime: 10,
    maxPortions: 30,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-05T06:00:00.000Z',
  },
  {
    id: 'dish-29',
    kitchenId: 'kitchen-6',
    name: 'عصير مانجو',
    nameEn: 'Mango Juice',
    description: 'عصير مانجو طازة',
    descriptionEn: 'Fresh mango juice',
    price: 30,
    category: 'مشروبات',
    categoryEn: 'Drinks',
    prepTime: 5,
    maxPortions: 25,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-05T06:00:00.000Z',
  },
  {
    id: 'dish-30',
    kitchenId: 'kitchen-6',
    name: 'فطيرة سبانخ',
    nameEn: 'Spinach Pie',
    description: 'فطيرة سبانخ بالجبنة والسمسم',
    descriptionEn: 'Spinach pie with cheese and sesame',
    price: 35,
    category: 'فطائر',
    categoryEn: 'Pastries',
    prepTime: 20,
    maxPortions: 18,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-05T06:00:00.000Z',
  },
  // Extra dishes for kitchen 1 to reach 6+ per kitchen
  {
    id: 'dish-31',
    kitchenId: 'kitchen-1',
    name: 'ملوخية',
    nameEn: 'Molokhia',
    description: 'ملوخية خضرا بالأرنب أو الفراخ',
    descriptionEn: 'Green molokhia with rabbit or chicken',
    price: 85,
    category: 'أصناف رئيسية',
    categoryEn: 'Main Dishes',
    prepTime: 40,
    maxPortions: 12,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-10T08:00:00.000Z',
  },
  {
    id: 'dish-32',
    kitchenId: 'kitchen-1',
    name: 'شاي',
    nameEn: 'Tea',
    description: 'شاي أسود بالسكر',
    descriptionEn: 'Black tea with sugar',
    price: 15,
    category: 'مشروبات',
    categoryEn: 'Drinks',
    prepTime: 5,
    maxPortions: 50,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-10T08:00:00.000Z',
  },
  // Extra dishes for kitchen 3
  {
    id: 'dish-33',
    kitchenId: 'kitchen-3',
    name: 'شاي حلويات',
    nameEn: 'Dessert Tea',
    description: 'شاي بالنعناع مع الحلويات الشرقية',
    descriptionEn: 'Mint tea with oriental sweets',
    price: 30,
    category: 'مشروبات',
    categoryEn: 'Drinks',
    prepTime: 5,
    maxPortions: 30,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-08T09:00:00.000Z',
  },
  // Extra dishes for kitchen 4
  {
    id: 'dish-34',
    kitchenId: 'kitchen-4',
    name: 'بيض بالطماطم',
    nameEn: 'Shakshouka',
    description: 'بيض بالطماطم والفلفل الحار',
    descriptionEn: 'Eggs in spicy tomato sauce',
    price: 45,
    category: 'أصناف رئيسية',
    categoryEn: 'Main Dishes',
    prepTime: 15,
    maxPortions: 15,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-07T11:00:00.000Z',
  },
  {
    id: 'dish-35',
    kitchenId: 'kitchen-4',
    name: 'بطاطس محمرة',
    nameEn: 'Fried Potatoes',
    description: 'بطاطس محمرة مقرمشة',
    descriptionEn: 'Crispy fried potatoes',
    price: 30,
    category: 'مقبلات',
    categoryEn: 'Appetizers',
    prepTime: 15,
    maxPortions: 20,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-07T11:00:00.000Z',
  },
  // Extra dish for kitchen 5
  {
    id: 'dish-36',
    kitchenId: 'kitchen-5',
    name: 'فتة بالخل والتوم',
    nameEn: 'Fatta with Vinegar and Garlic',
    description: 'فتة بالخل والتوم والأرز',
    descriptionEn: 'Fatta with vinegar, garlic, and rice',
    price: 70,
    category: 'أصناف رئيسية',
    categoryEn: 'Main Dishes',
    prepTime: 30,
    maxPortions: 10,
    available: true,
    imageUrl: null,
    createdAt: '2026-04-06T07:00:00.000Z',
  },
];
