import type { Kitchen } from '@/types';

export const KITCHEN_SEEDS: Kitchen[] = [
  {
    id: 'kitchen-1',
    chefId: 'chef-01000000001',
    name: 'مطبخ أم سمية',
    nameEn: "Umm Samia's Kitchen",
    bio: 'أكل بيتي مصري أصيل زي ما ماما كانت بتعمله',
    bioEn: 'Authentic Egyptian home cooking just like mom used to make',
    cuisineTags: ['مصري', 'مشويات'],
    area: 'Maadi',
    rating: 4.7,
    reviewCount: 5,
    isVerified: true,
    coverImage: 'placeholder',
    isOpen: true,
    createdAt: '2026-04-10T08:00:00.000Z',
  },
  {
    id: 'kitchen-2',
    chefId: 'chef-01000000002',
    name: 'مطبخ حاج محمد',
    nameEn: "Haj Mohamed's Kitchen",
    bio: 'مشويات بلدي طازة من الحلال يوميتك',
    bioEn: 'Fresh halal grills made daily with love and tradition',
    cuisineTags: ['مصري', 'مشويات', 'فطائر'],
    area: 'Zamalek',
    rating: 4.5,
    reviewCount: 4,
    isVerified: true,
    coverImage: 'placeholder',
    isOpen: true,
    createdAt: '2026-04-09T10:00:00.000Z',
  },
  {
    id: 'kitchen-3',
    chefId: 'chef-01000000003',
    name: 'مطبخ ست نونه',
    nameEn: "Sit Nona's Kitchen",
    bio: 'حلويات ومأكولات شرقية بالطريقة اللي الجدة كانت بتعملها',
    bioEn: 'Oriental sweets and dishes made the way grandma used to',
    cuisineTags: ['حلويات', 'مصري'],
    area: 'Heliopolis',
    rating: 4.9,
    reviewCount: 5,
    isVerified: true,
    coverImage: 'placeholder',
    isOpen: true,
    createdAt: '2026-04-08T09:00:00.000Z',
  },
  {
    id: 'kitchen-4',
    chefId: 'chef-01000000004',
    name: 'أكل البيت',
    nameEn: 'Home Food',
    bio: 'وجبات يومية صحية طازة كل يوم',
    bioEn: 'Fresh healthy daily meals every day',
    cuisineTags: ['مصري', 'أصناف رئيسية'],
    area: 'Nasr City',
    rating: 4.2,
    reviewCount: 3,
    isVerified: false,
    coverImage: 'placeholder',
    isOpen: true,
    createdAt: '2026-04-07T11:00:00.000Z',
  },
  {
    id: 'kitchen-5',
    chefId: 'chef-01000000005',
    name: 'مطبخ السيدة',
    nameEn: "Al Sayeda's Kitchen",
    bio: 'شوربات ومأكولات دافية في الشتا والصيف',
    bioEn: 'Warm soups and comfort food for winter and summer',
    cuisineTags: ['شوربات', 'مصري', 'سلطات'],
    area: 'New Cairo',
    rating: 4.3,
    reviewCount: 3,
    isVerified: false,
    coverImage: 'placeholder',
    isOpen: true,
    createdAt: '2026-04-06T07:00:00.000Z',
  },
  {
    id: 'kitchen-6',
    chefId: 'chef-01000000006',
    name: 'فرن المعجنات',
    nameEn: 'Pastry Oven',
    bio: 'فطائر ومعجنات طازة كل صباح',
    bioEn: 'Fresh pastries and pies every morning',
    cuisineTags: ['فطائر', 'مشروبات'],
    area: '6th October',
    rating: 4.6,
    reviewCount: 4,
    isVerified: true,
    coverImage: 'placeholder',
    isOpen: true,
    createdAt: '2026-04-05T06:00:00.000Z',
  },
];
